CREATE TABLE IF NOT EXISTS trips (
  trip_id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  rider_id INT NOT NULL,
  driver_id INT,
  pickup_zone TEXT NOT NULL,
  drop_zone TEXT NOT NULL,
  status TEXT NOT NULL,
  requested_at TIMESTAMP NOT NULL,
  distance_km NUMERIC,
  base_fare NUMERIC,
  surge_multiplier NUMERIC,
  total_fare NUMERIC
);